### ISSUE TITLE
Permission denied when opening tex file

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/latexml-snap#12]
Something wrong with latexml installation via `snap`

1. `cpanm`'s installation works https://github.com/metanorma/mn-samples-tex-iso/runs/503117809
2. the same with snap doesn't work https://github.com/metanorma/mn-samples-tex-iso/actions/runs/54315269

Full-stack trace:

```
Fatal:I/O:open Can't open /home/runner/work/mn-samples-tex-iso/mn-samples-tex-iso/sections-en/b0-bibliography.tex for reading
	at b0-bibliography.tex
	Permission denied
	Stack Trace:
		Mouth[/home/runner/work/mn-samples-te...->openFile('/home/runner/work/mn-samples-tex-iso...) @ /snap/latexml/15/usr/local/share/perl/5.22.1/LaTeXML/Core/Mouth/file.pm line 27
	LaTeXML::Core::Mouth::file::new('LaTeXML::Core::Mouth::file','/home/runner/work/mn-samples-tex-iso...,'notes',1,'content',undef) @ /snap/latexml/15/usr/local/share/perl/5.22.1/LaTeXML/Core/Mouth.pm line 48
	LaTeXML::Core::Mouth::create('LaTeXML::Core::Mouth','/home/runner/work/mn-samples-tex-iso...,'notes',1,'content',undef) @ /snap/latexml/15/usr/local/share/perl/5.22.1/LaTeXML/Package.pm line 1994
	LaTeXML::Package::loadTeXContent('/home/runner/work/mn-samples-tex-iso...) @ /snap/latexml/15/usr/local/share/perl/5.22.1/LaTeXML/Package.pm line 1853
	LaTeXML::Package::InputContent('/home/runner/work/mn-samples-tex-iso...) @ /snap/latexml/15/usr/local/share/perl/5.22.1/LaTeXML/Core.pm line 148
	LaTeXML::Core::__ANON__(LaTeXML::Core::State=HASH(0x49bc638)) @ /snap/latexml/15/usr/local/share/perl/5.22.1/LaTeXML/Core.pm line 245
	Core[@0x4c2aa68]->withState(CODE(0x4c2abe8)) @ /snap/latexml/15/usr/local/share/perl/5.22.1/LaTeXML/Core.pm line 157
	Core[@0x4c2aa68]->digestFile('sections-en/b0-bibliography.tex','mode','TeX','preamble',undef,'postamble',undef) @ /snap/latexml/15/usr/local/bin/latexml line 103
	eval {...} @ /snap/latexml/15/usr/local/bin/latexml line 98
```

**Comment by ronaldtse** [comment]
Ahh I think Snap installations are jailed like a container.

**Comment by ronaldtse** [comment]
* https://forum.snapcraft.io/t/permission-denied-when-trying-to-access-user-files/7413
* https://forum.snapcraft.io/t/solved-permission-denied-in-general-ubuntu-19-10-snap-2-42-5/15161

**Comment by ronaldtse** [comment]
https://askubuntu.com/questions/930437/permission-denied-error-when-running-apps-installed-as-snap-packages-ubuntu-17

**Comment by ronaldtse** [comment]
I think it's exactly this one! https://forum.snapcraft.io/t/permission-denied-when-installing-jq-using-snap/15030

> FWIW the snap could have asked for the "home"[1] interface, which would have allowed it access to files in your home folder - but not those hidden (or in hidden directories).
[1] https://snapcraft.io/docs/home-interface

**Comment by CAMOBAP** [comment]
Merged, doing new `--edge` release
