### ISSUE TITLE
Update secrets.snapcraft_token

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/latexml-snap#14]
@ronaldtse could you please doublecheck `secrets.snapcraft_token` looks like it's missing or invalid

**Comment by ronaldtse** [comment]
It's secrets.SNAPCRAFT_TOKEN, can you check if it is case sensitive?

**Comment by CAMOBAP** [comment]
@ronaldtse something still isn't right, could you please confirm that both `secrets.snapcraft_token` are the same for https://github.com/metanorma/latexml-snap and https://github.com/metanorma/metanorma-snap

**Comment by ronaldtse** [comment]
I will regenerate the token using https://github.com/metanorma/metanorma-snap#generating-the-snapcraft-token

**Comment by ronaldtse** [comment]
Updated to use secrets.METANORMA_SNAPCRAFT_TOKEN

**Comment by ronaldtse** [comment]
Updated in 11e8b537f7b639a5e1050ae4d6bf480eff12cabf.
