### ISSUE TITLE
Update CI config

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/latexml-snap#2]
@ronaldtse I need your help

1. register latexml snap from metanorma org
2. update .travis.yml for this project by `snapcraft enable-ci travis --refresh`

Just create PR I will resolve conflicts on my own

**Comment by ronaldtse** [comment]
@CAMOBAP795 we now have registered the latexml snap.

Anything else should I do?

**Comment by CAMOBAP** [comment]
@ronaldtse please run `snapcraft enable-ci travis --refresh` on this repo to generate new .travis.yml & to add security variables which will allow me to setup push from CI

**Comment by ronaldtse** [comment]
@CAMOBAP795 everything is set in Travis. Can you proceed with this?

**Comment by ronaldtse** [comment]
Ping @CAMOBAP795

**Comment by ronaldtse** [comment]
@CAMOBAP795 I've run the command it seems to work now. Can you please confirm?

**Comment by ronaldtse** [comment]
@CAMOBAP795 the Travis config now works. Can you help release it ASAP? Thanks.

**Comment by CAMOBAP** [comment]
@ronaldtse 

I'm not sure because now `openssl` failed
```
$ openssl aes-256-cbc -K $encrypted_733e17776623_key -iv $encrypted_733e17776623_iv -in snap_token.enc -out snap_token -d
bad decrypt
```

**Comment by ronaldtse** [comment]
@CAMOBAP795 the travis link is wrong, it should be a dot-com:

https://travis-ci.com/metanorma/latexml-snap

I'm trying to run again.

**Comment by ronaldtse** [comment]
@CAMOBAP795 looks like the snap is built, the message is now:

```
Skipping a deployment with the script provider because this is not a tagged commit
```

**Comment by CAMOBAP** [comment]
@ronaldtse right because like on metanorma-docker we don't upload snap on any commit, we upload only for tagged commits, so let me retag
