### ISSUE TITLE
Authorization for LaTeXML snap package

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/latexml-snap#3]
The Snap team wishes to verify that we are authorized to publish the [LaTeXML](https://github.com/brucemiller/LaTeXML) snap package, on a GitHub issue.

@brucemiller could you please help confirm here? Thank you!

**Comment by brucemiller** [comment]
Yep, I'm good with that! Confirming. Thanks!

**Comment by ronaldtse** [comment]
Thank you @brucemiller !
