### ISSUE TITLE
Move from Travis to GitHub Actions

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/latexml-snap#6]
@CAMOBAP795 with the recent failures I suspect we should directly move to GHA to resolve this problem:

https://boxofcables.dev/snaps-for-nim/

**Comment by CAMOBAP** [comment]
@ronaldtse could you please add secret variables:
 - `$encrypted_733e17776623_key`
 - `$encrypted_733e17776623_iv`

The same as on travis

**Comment by ronaldtse** [comment]
Those variables were actually made by Travis, so I will need to re-generate the Snap credentials. Will do that today.

**Comment by CAMOBAP** [comment]
What I found out:
 - `snapd` doesn't work in docker
 - `multipass` doesn't work in docker
 - `multipass` cannot run in non-docerized machine (on GH Actions)
 - `snapd` works in non-dockerized machine (on GH Actions)

I have tried to use `snapcore/snapcraft:stable`for build job &  regular `ubuntu-latest` to test install - it works

@ronaldtse actually we don't need two variables there, here is what we need https://github.com/marketplace/actions/snapcraft-action#log-in

**Comment by ronaldtse** [comment]
Good find, I will provide the snapcraft token as a secret under “SNAPCRAFT_TOKEN”.

**Comment by ronaldtse** [comment]
@CAMOBAP795 this is done -- the Snapcraft token is now `{{ secrets.snapcraft_token }}`

**Comment by ronaldtse** [comment]
Changed to use GH Action here: 6c3633932b4842c3ee3ba1504a35c7058952bbea

**Comment by CAMOBAP** [comment]
Merged
