### ISSUE TITLE
Missing `latexmlmath` executable

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/latexml-snap#8]
In this GH action the `latexmlmath` executable does not seem to be installed alongside the snap package: https://github.com/metanorma/metanorma-standoc/runs/249378650

@CAMOBAP795 can you please help check? Thanks.

```
Errno::ENOENT:
No such file or directory - latexmlmath
./lib/asciidoctor/standoc/inline.rb:113:in `popen'
./lib/asciidoctor/standoc/inline.rb:113:in `stem_parse'
./lib/asciidoctor/standoc/inline.rb:137:in `block in inline_quoted'
./lib/asciidoctor/standoc/utils.rb:165:in `noko'
./lib/asciidoctor/standoc/inline.rb:127:in `inline_quoted'
./lib/asciidoctor/standoc/utils.rb:145:in `convert'
./lib/asciidoctor/standoc/blocks.rb:217:in `block (2 levels) in paragraph'
./lib/asciidoctor/standoc/blocks.rb:216:in `block in paragraph'
./lib/asciidoctor/standoc/utils.rb:165:in `noko'
./lib/asciidoctor/standoc/blocks.rb:215:in `paragraph'
./lib/asciidoctor/standoc/utils.rb:145:in `convert'
./lib/asciidoctor/standoc/base.rb:190:in `block in middle'
./lib/asciidoctor/standoc/base.rb:189:in `middle'
./lib/asciidoctor/standoc/base.rb:161:in `block in makexml1'
./lib/asciidoctor/standoc/utils.rb:165:in `noko'
./lib/asciidoctor/standoc/base.rb:161:in `makexml1'
./lib/asciidoctor/standoc/base.rb:167:in `makexml'
./lib/asciidoctor/standoc/base.rb:148:in `document'
```

**Comment by CAMOBAP** [comment]
@ronaldtse I will check it because I didn't find a way pack `latexmlmath`, but `latexml.math` is available there

**Comment by ronaldtse** [comment]
@CAMOBAP795 `latexmlmath` is directly used by metanorma so we ought to fix that first. Worse to worst we can make a symbolic link for it?

**Comment by CAMOBAP** [comment]
@ronaldtse right I missed this because before we tried `latexml` with a list of options, but I forgot that we moved back to `latexmlmath`, I looking for a way to fix it on snap side

**Comment by CAMOBAP** [comment]
There is aliases mechanism in snapcraft, https://forum.snapcraft.io/t/commands-and-aliases/3950 investigation in progress

**Comment by CAMOBAP** [comment]
https://forum.snapcraft.io/t/add-default-aliases-for-latexml-package/13562 - default aliases requested

**Comment by ronaldtse** [comment]
Does snap not support aliased executables? Or does it have to use the name of the snap?

**Comment by CAMOBAP** [comment]
> Does snap not support aliased executables?

Support two different types of aliases:
 - Manual
 - Automatic

Example of manual alias is - https://github.com/metanorma/metanorma-standoc/pull/123/files#diff-a77b4f53dac18d1e289021f245022811R32

For automatic we need to get approvement from https://forum.snapcraft.io/t/add-default-aliases-for-latexml-package/13562

**Comment by CAMOBAP** [comment]
3 days left for aliases approval

**Comment by ronaldtse** [comment]
Apparently this has been approved 5 days ago. Thanks!

<img width="781" alt="Screen Shot 2019-10-28 at 12 12 34 PM" src="https://user-images.githubusercontent.com/11865/67651487-39a6bb80-f97c-11e9-9fad-5d1859c62b3f.png">
