### ISSUE TITLE
Create LaTeXML edge version

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/latexml-snap#9]
The `tex2mn` tool, for example, relies on the latest LaTeXML version. We need to create an "edge" channel based on the latest LaTeXML git repo.

@brucemiller what do you think we should do with regard to edge releases?

**Comment by CAMOBAP** [comment]
@ronaldtse  https://github.com/metanorma/latexml-snap/pull/10 done

**Comment by ronaldtse** [comment]
Thank you @CAMOBAP795 !

**Comment by CAMOBAP** [comment]
@ronaldtse ideally we should 'listen' for any commit to `master` on https://github.com/brucemiller/LaTeXML

But for now, it's impossible to do it in 'safe' way 
 - https://github.community/t5/GitHub-Actions/Triggering-by-other-repository/m-p/30668

Research in progress

**Comment by CAMOBAP** [comment]
Looks like https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows#scheduled-events-schedule is a good option in this case

Let's have a cron for let's say twice a weak

@ronaldtse @brucemiller how do you think?

**Comment by CAMOBAP** [comment]
can be reopened if need
